update utils/console

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,8 +1,7 @@
 #!/bin/bash
 # cenbia main build script: nawawi@rutweb.com
 
-. ./build.d/bootstrap.sh;
-[ -z "${_BOOTSTRAP}" ] && { echo "Load failed"; exit 1; };
+. ./build.d/bootstrap.sh &>/dev/null || { echo "Bootstrap failed"; exit 1; };
 
 # functions
 _echo() {
@@ -72,7 +71,7 @@ _REBUILD="${_REBUILD:-"no"}";
 # mandatory
 _UTILS_BIN="curl openssl iconv php php-fpm php-cgi ";
 _UTILS_BIN+="httpd mysqld mysql checkport ";
-_UTILS_BIN+="cenbia cenbia-first-setup cenbia-start cenbia-stop cenbia-restart";
+_UTILS_BIN+="cenbia";
 
 export _CENBIA_VERSION="$(< $_BUILD_PATH/build.d/cenbia-version)";
 export _CENBIA_BUILD_PATH=$_BUILD_PATH;
@@ -319,40 +318,6 @@ _FINISH() {
                 rm -rf $_CENBIA_INST_PATH/bin/.tmp
             fi
         fi
-    fi
-
-    if [ -f "${_BUILD_PATH}/build.d/cenbia-environment" ]; then
-        [ ! -d "${_CENBIA_INST_PATH}/etc" ] && mkdir -p  $_CENBIA_INST_PATH/etc;
-        cp -f ${_BUILD_PATH}/build.d/cenbia-environment $_CENBIA_INST_PATH/etc/cenbia-environment;
-        sed -i -e "s|@INST_DIR|$_CENBIA_INST_PATH|g" $_CENBIA_INST_PATH/etc/cenbia-environment;
-        sed -i -e "s|@ROOT_DIR|$_CENBIA_ROOT_PATH|g" $_CENBIA_INST_PATH/etc/cenbia-environment;
-    fi
-    if [ -f "${_BUILD_PATH}/build.d/console.sh" ]; then
-        _cbin="${_CENBIA_ROOT_PATH}/cenbia";
-        cp -f ${_BUILD_PATH}/build.d/console.sh $_cbin;
-        sed -i -e "s|@ROOT_DIR|$_CENBIA_ROOT_PATH|g" $_cbin;
-        sed -i -e "s|@INST_DIR|$_CENBIA_INST_PATH|g" $_cbin;
-        chmod 755 $_cbin;
-    fi
-    if [ -f "${_BUILD_PATH}/build.d/cenbia-start.sh" ]; then
-        _cbin="${_CENBIA_INST_PATH}/bin/cenbia-start";
-        cp -f ${_BUILD_PATH}/build.d/cenbia-start.sh $_cbin;
-        sed -i -e "s|@ROOT_DIR|$_CENBIA_ROOT_PATH|g" $_cbin;
-        sed -i -e "s|@INST_DIR|$_CENBIA_INST_PATH|g" $_cbin;
-        chmod 755 $_cbin;
-        cwd=$(pwd);
-        if cd $_CENBIA_INST_PATH/bin; then
-            ln -sf cenbia-start cenbia-stop;
-            ln -sf cenbia-start cenbia-restart;
-            cd $cwd;
-        fi
-    fi
-    if [ -f "${_BUILD_PATH}/build.d/cenbia-first-setup.sh" ]; then
-        _cbin="${_CENBIA_INST_PATH}/bin/cenbia-first-setup";
-        cp -f ${_BUILD_PATH}/build.d/cenbia-first-setup.sh $_cbin;
-        sed -i -e "s|@ROOT_DIR|$_CENBIA_ROOT_PATH|g" $_cbin;
-        sed -i -e "s|@INST_DIR|$_CENBIA_INST_PATH|g" $_cbin;
-        chmod 755 $_cbin;
     fi
 
     [ -d "${_CENBIA_INST_PATH}/etc/init.d" ] && rm -rf $_CENBIA_INST_PATH/etc/init.d;
diff --git a/source/httpd/patches/httpd-control b/source/httpd/patches/httpd-control
--- a/source/httpd/patches/httpd-control
+++ b/source/httpd/patches/httpd-control
@@ -1,6 +1,5 @@
 #!/bin/bash
-source @INST_DIR/etc/cenbia-environment &>/dev/null || { echo "Failed to load library"; exit 1; };
-export LD_LIBRARY_PATH="@INST_DIR/lib/httpd:${LD_LIBRARY_PATH}";
+source @ROOT_DIR/scripts/bootstrap.sh &>/dev/null || { echo "Bootstrap failed"; exit 1; };
 
 ulimit -HSn 32768;
 
@@ -40,7 +39,7 @@ stop() {
 	    return 0;
 	fi
     _msg "Stopping $prog.";
-    HTTPPID="$(cat $pidfile)";
+    HTTPPID="$(< $pidfile)";
 	if [ -n "$HTTPPID" ]; then
         $httpd -k stop &>/dev/null;
 	    ret=$?;
@@ -77,7 +76,7 @@ stop() {
 reload() {
     _msg "Reloading $prog.";
     if [ -f "$pidfile" ]; then
-        HTTPPID="$(cat $pidfile)";
+        HTTPPID="$(< $pidfile)";
         if kill -HUP $HTTPPID 2>/dev/null ; then 
             _success;
             exit 0;
@@ -99,7 +98,7 @@ reload() {
 
 status() {
     if [ -f "$pidfile" ]; then
-        HTTPPID="$(cat $pidfile)";
+        HTTPPID="$(< $pidfile)";
         if kill -0 $HTTPPID 2>/dev/null ; then 
             echo "HTTPD running ($HTTPPID)";
             exit 0;
diff --git a/source/mariadb/patches/mysqld-control b/source/mariadb/patches/mysqld-control
--- a/source/mariadb/patches/mysqld-control
+++ b/source/mariadb/patches/mysqld-control
@@ -1,5 +1,5 @@
 #!/bin/bash
-source @INST_DIR/etc/cenbia-environment &>/dev/null || { echo "Failed to load library"; exit 1; };
+source @ROOT_DIR/scripts/bootstrap.sh &>/dev/null || { echo "Bootstrap failed"; exit 1; };
 user="@USER";
 group="@USER";
 basedir="@INST_DIR";
@@ -112,7 +112,7 @@ stop() {
 	    return 0;
 	fi
     _msg "Stopping $prog";
-    MYSQLPID="$(cat $mypidfile)";
+    MYSQLPID="$(< $mypidfile)";
 	if [ -n "$MYSQLPID" ]; then
 	    kill "$MYSQLPID" >/dev/null 2>&1
 	    ret=$?;
@@ -149,7 +149,7 @@ restart(){
 
 status() {
     if [ -f "$mypidfile" ]; then
-        MYSQLPID="$(cat $mypidfile)";
+        MYSQLPID="$(< $mypidfile)";
         if kill -0 $MYSQLPID 2>/dev/null ; then 
             echo "MySQL running ($MYSQLPID)";
             exit 0;
@@ -171,7 +171,7 @@ status() {
 reload() {
     _msg "Reloading service MySQL";
     if [ -f "$mypidfile" ]; then
-        MYSQLPID="$(cat $mypidfile)";
+        MYSQLPID="$(< $mypidfile)";
         if kill -HUP $MYSQLPID 2>/dev/null ; then 
             _success;
             exit 0;
